# Generate the Climatescope basemap from the meta/admin_areas.csv

# Every time, a country is added or removed from the Climatescope, a new
# basemap needs to be generated and uploaded to Mapbox. To do so, follow
# these steps:
#
# 1. run this script
#       $ bash generate_basemap.sh
# 2. log in to Mapbox and replace the Tileset climatescope-basemap with the
#    GeoJSON that was generated by this script


mkdir tmp
wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip -O ./tmp/ne_10m.zip
unzip ./tmp/ne_10m.zip -d ./tmp
ogr2ogr -f "GeoJSON" ./tmp/ne10.json ./tmp/ne_10m_admin_0_countries.shp
node generate-cs-basemap.js
rm -r tmp