# Generate the Climatescope basemap from the meta/admin_areas.csv

# Every time, a country is added or removed from the Climatescope, a new
# basemap needs to be generated and uploaded to Mapbox. To do so, follow
# these steps:
#
# 1. run this script
#       $ bash generate_basemap.sh
# 2. log in to Mapbox and replace the Tileset climatescope-basemap with the
#    mbtiles file that was generated by this script


mkdir tmp
wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip -O ./tmp/ne_10m.zip
wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_boundary_lines_land.zip -O ./tmp/ne_10m_lines.zip
unzip ./tmp/ne_10m.zip -d ./tmp
unzip ./tmp/ne_10m_lines.zip -d ./tmp
ogr2ogr -f "GeoJSON" ./tmp/ne10.json ./tmp/ne_10m_admin_0_countries.shp
ogr2ogr -f "GeoJSON" ./tmp/ne10_lines.json ./tmp/ne_10m_admin_0_boundary_lines_land.shp
node process-json.js
tippecanoe -o cs-basemap.mbtiles -Z 0 -z 6 ./tmp/climatescope-basemap-data.json 
tippecanoe -o cs-basemap-lines.mbtiles -Z 0 -z 6 ./tmp/ne10_lines.json 
rm -r tmp